export const ROLES = {
  ADMIN: "admin",
  MANAGER: "manager",
  AST_MANAGER: "ast_manager",
  ENGINEER: "engineer",
} as const;

export const PERMISSIONS = {
  DASHBOARD_VIEW: [
    ROLES.ADMIN,
    ROLES.MANAGER,
    ROLES.AST_MANAGER,
    ROLES.ENGINEER,
  ],
  DASHBOARD_FULL_ACCESS: [
    ROLES.ADMIN,
    ROLES.MANAGER,
    ROLES.AST_MANAGER,
    ROLES.ENGINEER,
  ],

  EQUIPMENT_VIEW: [
    ROLES.ADMIN,
    ROLES.MANAGER,
    ROLES.AST_MANAGER,
    ROLES.ENGINEER,
  ],
  EQUIPMENT_CREATE: [
    ROLES.ADMIN,
    ROLES.MANAGER,
    ROLES.AST_MANAGER,
    ROLES.ENGINEER,
  ],
  EQUIPMENT_EDIT: [
    ROLES.ADMIN,
    ROLES.MANAGER,
    ROLES.AST_MANAGER,
    ROLES.ENGINEER,
  ],
  EQUIPMENT_DELETE: [
    ROLES.ADMIN,
    ROLES.MANAGER,
    ROLES.AST_MANAGER,
    ROLES.ENGINEER,
  ],
  EQUIPMENT_ADD_DESCRIPTION: [
    ROLES.ADMIN,
    ROLES.MANAGER,
    ROLES.AST_MANAGER,
    ROLES.ENGINEER,
  ],


  STAFF_VIEW: [ROLES.ADMIN, ROLES.MANAGER],
  STAFF_CREATE: [ROLES.ADMIN, ROLES.MANAGER],
  STAFF_EDIT: [ROLES.ADMIN, ROLES.MANAGER],
  STAFF_DELETE: [ROLES.ADMIN, ROLES.MANAGER],


  EMAIL_SETTINGS: [ROLES.ADMIN, ROLES.MANAGER],


  REPORTS_VIEW: [ROLES.ADMIN, ROLES.MANAGER],


  SYSTEM_SETTINGS: [ROLES.ADMIN, ROLES.MANAGER],
} as const;
